INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Große-Stoltenberg,Andre', 444, 'Institute for Landscape Ecology', 362, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wertebach,Tim-Martin', 422, 'Institute for Landscape Ecology', 353, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Niklasch,Sebastian', 102, 'Institute for Geoinformatics', 227, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Busch,Verena', 512, 'Institute for Landscape Ecology', 379, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratoryatoty for hydrofluoric acid', 333, 'Fossil botany', 440, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Neumann,Frank', 328, 'Fossil botany', 323, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Otto,Karl-Heinz', 412, 'Geographic commission', 345, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room Geographic commission', 408, 'Geographic commission', 445, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Dörendahl,Ester', 403, 'Institute for Landscape Ecology', 336, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Keggenhoff,Katja', 344, 'Institute for Geography', 331, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Möllenbeck,Verena', 504, 'Institute for Landscape Ecology', 457, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Münch,Thorsten', 546, 'Institute for Landscape Ecology', 398, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fechner,Thore', 248, 'Institute for Geoinformatics', 506, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Du,Guiying', 235, 'Institute for Geoinformatics', 510, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kämpf,Immo', 7, 'Institute for Landscape Ecology', 383, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Mathar,Wanja', 422, 'Institute for Landscape Ecology', 514, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Scherber, Dr.,Christoph', 536, 'Institute for Landscape Ecology', 518, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Jonas,Gabi', 0.11, 'Library staff', 204, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('﻿Library,Assistants', 0.14, 'Library staff', 205, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kerp,Hans', 510, 'Dean', 377, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Mukhamentov,Sergej', 101, 'Institute for Geoinformatics', 226, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wirwahn,Jan', 101, 'Institute for Geoinformatics', 225, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Manel,Champika', 240, 'Institute for Geoinformatics', 507, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Bustamante Duarte,Ana Maria', 235, 'Institute for Geoinformatics', 511, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Ott, Dr.,David', 537, 'Institute for Landscape Ecology', 515, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Steinhäuser de Barba,Cornelia', 209, 'Institute for Landscape Ecology', 519, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Platz,Stefan', 17, 'IVV Geosciences', 216, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Student association Geo / Landscape Ecology', 23, 'Student association', 219, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Härtl,Nadine', 304, 'Institute for Geography', 310, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fachschaft Geoinformatik', 24, 'Fachschaft', 221, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Holthaus,Malte', 17, 'IVV Geosciences', 218, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Robben,Norbert', 17, 'IVV Geosciences', 217, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Anacta,Vanessa Joy', 111, 'Institute for Geoinformatics', 240, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Student association Geoinformatics', 24, 'Student association', 222, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fachschaft Geo/Lök', 23, 'Fachschaft', 220, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Busch,Eugen', 26, 'Facility Management', 224, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wesseler,Dietmar', 26, 'Facility Management', 223, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Jan,Sahib', 112, 'Institute for Geoinformatics', 241, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Camara,Gilberto', 113, 'Institute for Geoinformatics', 242, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Sanchez,Albert', 114, 'Institute for Geoinformatics', 243, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Buurmann,Merret', 114, 'Institute for Geoinformatics', 244, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Brox,Christoph', 115, 'Institute for Geoinformatics', 245, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Van Zadelhoff,Jan', 117, 'Institute for Geoinformatics', 247, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Remke,Albert', 120, 'Institute for Geoinformatics', 248, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wiefel,Heike', 123, 'Institute for Geoinformatics', 250, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Höwelhans,Karsten', 123, 'Institute for Geoinformatics', 251, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Versmold,Christina', 123, 'Institute for Geoinformatics', 249, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wöltje,Katrin', 124, 'Front-Office', 255, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Torres Matallana,Jairo Arturo', 141, 'Institute for Geoinformatics', 269, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Front-Office', 124, 'Front-Office', 253, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gabel,Friederike', 124, 'Front-Office', 254, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wrenger,Katja', 124, 'Front-Office', 252, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Pebesma,Edzer', 131, 'Institute for Geoinformatics', 256, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Rehr,Mirjam', 132, 'Institute for Geoinformatics', 257, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Lu,Meng', 132, 'Institute for Geoinformatics', 258, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Sidhu,Nanki', 133, 'Institute for Geoinformatics', 260, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Lahn,Florian', 133, 'Institute for Geoinformatics', 259, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Knoth,Christian', 137, 'Institute for Geoinformatics', 262, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gräler,Benedikt', 138, 'Institute for Geoinformatics', 263, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Nüst,Daniel', 135, 'Institute for Geoinformatics', 266, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Stasch,Christoph', 139, 'Institute for Geoinformatics', 264, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('STML,Assistants', 141, 'Institute for Geoinformatics', 267, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gerding,Cathleen', 0.16, 'Library staff', 206, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Maus,Victor', 141, 'Institute for Geoinformatics', 268, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Weinauer,Julia', 202, 'Institute for Geoinformatics', 271, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wrobel,Agnes', 204, 'Dean Chemistry', 275, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Lehmann,Jan', 204, 'Institute for Landscape Ecology', 274, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Stute,Christiana', 204, 'Dean Chemistry', 273, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Padgham,Mark', 214, 'Institute for Geoinformatics', 276, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schlattmann,Stefan', 214, 'Miscellaneous', 277, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Scheider,Simon', 215, 'Institute for Geoinformatics', 279, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Herwig,Sebastian (Dr.)', 215, 'Miscellaneous', 278, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Braun,Alexander', 217, 'Institute for Didactics of Geography', 281, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wrenger,Katja', 219, 'Institute for Didactics of Geography', 282, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kuhmann,Daniel', 221, 'Institute for Didactics of Geography', 283, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Steinau,Heike', 224, 'Institute for Didactics of Geography', 284, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Bette,Julian', 226, 'Institute for Didactics of Geography', 285, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schubert,Jan Christoph', 229, 'Institute for Didactics of Geography', 287, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Brendel,Nina', 227, 'Institute for Didactics of Geography', 286, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hemmer,Michael', 230, 'Institute for Didactics of Geography', 288, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wissing,Jens', 234, 'Institute for Geoinformatics', 291, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Banhatti,Gautam Dilip', 234, 'Institute for Geoinformatics', 290, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Degbelo,Auriol', 238, 'Institute for Geoinformatics', 297, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Adeva,Elisabet', 245, 'Institute for Geoinformatics', 296, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kray,Christian', 241, 'Institute for Geoinformatics', 299, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fritze,Holger', 247, 'Institute for Geoinformatics', 301, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Boehmichen,Jeannine', 249, 'Institute for Landscape Ecology', 304, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gottwald,Marc', 302, 'Institute for Geography', 307, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wood,Gerald', 301, 'Institute for Geography', 306, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kobras,Martina', 306, 'Institute for Geography', 313, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Waltering,Michelle', 304, 'Institute for Geography', 309, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Reuber,Paul', 311, 'Institute for Geography', 315, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Linnemann,Kirsten', 307, 'Institute for Geography', 314, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kubiak,Susanne', 306, 'Institute for Geography', 312, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Niemann,Patrick', 312, 'Institute for Geography', 316, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Weichbrodt,Michael', 313, 'Institute for Geography', 318, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Brinkschröder,Michael', 312, 'Institute for Geography', 317, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Scheuplein,Christoph', 303, 'Institute for Geography', 308, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Richter,Julia', 315, 'Institute for Geography', 320, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kearney,Patricia', 322, 'Fossil botany', 321, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kerp,Johannes', 326, 'Fossil botany', 322, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schroer,Claudia', 335, 'Institute for Geography', 325, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Niehus,Anne', 328, 'Fossil botany', 324, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Werring,Jana', 336, 'Institute for Geography', 326, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Foerster,Jan', 339, 'Institute for Geography', 328, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Waitzinger,Hannah', 342, 'Institute for Geography', 330, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Lenk,Karsten', 346, 'Institute for Geography', 332, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Group room Library 0.19', 0.19, 'Library', 409, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kreulich,Gabriele', 3, 'Common section', 208, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Group room Library 0.20', 0.20, 'Library', 410, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Köneke,Vera', 4, 'Common Section', 210, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Scharffenstein,Nele', 4, 'Common section', 211, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Möllenbeck,Verena', 4, 'Common section', 209, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schimkat,Julia', 7, 'Electronic Factory', 212, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Learning studio', 10, 'Institute for Didactics of Geography', 413, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('ZDM (Zentrum Digitaler Medien)', 11, 'Zentrum Digitaler Medien (ZDM)', 414, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Prinz,Torsten', 16, 'IVV Geosciences', 215, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Broelemann,Klaus', 109, 'Institute for Geoinformatics', 237, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meijer,Marike', 102, 'Institute for Geoinformatics', 228, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 426, 'Institute for Landscape Ecology', 449, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 425, 'Institute for Landscape Ecology', 448, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 423, 'Institute for Landscape Ecology', 446, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room small 110', 110, 'Meeting', 416, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kamp, Dr.,Johannes', 249, 'Institute for Landscape Ecology', 372, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Malkus, Dr.,Andreas', 181, 'Institute for Landscape Ecology', 356, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Thiele, Dr.,Jan', 165, 'Institute for Landscape Ecology', 352, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kisfeld,Christoph', 117, 'Institute for Geoinformatics', 246, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('StudLab 125', 125, 'StudLab', 417, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('StudLab 126', 126, 'StudLab', 418, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schoemaker,Simon', 135, 'Institute for Geoinformatics', 261, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room', 228, 'Institute for Didactics of Geography', 424, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Assistants Institute for Didactics of Geography', 232, 'Institute for Didactics of Geography', 426, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room small 352', 352, 'Meeting', 443, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Situated Computing Lab (SitCom)', 245, 'Institute for Geoinformatics', 427, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Assistants study group Reuber', 308, 'Institute for Geography', 429, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Seminar 323', 323, 'Seminar room', 436, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Assistants study group Kerp', 324, 'Fossil botany', 437, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratoryatory of rocks', 331, 'Fossil botany', 438, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratoryatory of rocks', 332, 'Fossil botany', 439, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('AnthropoLab', 334, 'Institute for Geography', 441, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Grabski-Kieron,Ulrike', 338, 'Institute for Geography', 327, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Raabe,Mathias', 339, 'Institute for Geography', 329, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Assistance study group Grabski-Kieron', 340, 'Institute for Geography', 442, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room large 309', 309, 'Meeting', 430, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Seminar 401', 401, 'Seminar room', 444, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Eibes,Pia', 402, 'Erasmus-Office', 333, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Erasmus-Office', 402, 'Institute for Landscape Ecology and Geography', 334, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Biro,Beatrice', 402, 'Erasmus-Office', 335, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schmidt,Jenny', 403, 'Institute for Landscape Ecology', 338, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Yu,Zhiguo', 404, 'Institute for Landscape Ecology', 339, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fennhof,Kathrin', 407, 'Geographic commission', 342, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Bischoff,Carola', 409, 'Geographic commission', 343, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Grothues,Rudolf', 411, 'Geographic commission', 344, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Pohlmann,Horst', 413, 'Geographic commission', 346, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wieneke,Markus', 415, 'Geographic commission', 347, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Berning-Mader,Ulrike', 418, 'Institute for Landscape Ecology', 348, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Supper,Madeleine', 418, 'Institute for Landscape Ecology', 350, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Buttschardt,Tillmann', 419, 'Institute for Landscape Ecology', 351, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Knorr,Klaus-Holger', 438, 'Institute for Landscape Ecology', 357, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Wu,Yuanqiao', 439, 'Institute for Landscape Ecology', 358, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Agethen,Svenja', 441, 'Institute for Landscape Ecology', 360, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 427, 'Institute for Landscape Ecology', 450, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Goerzen-Kazmierczak,Ute', 445, 'Institute for Landscape Ecology', 363, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hollens,Hilke', 443, 'Institute for Landscape Ecology', 361, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gabel,Friederike', 447, 'Institute for Landscape Ecology', 364, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Keller,Philipp', 448, 'Institute for Landscape Ecology', 366, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Conrad,Helge', 449, 'Institute for Geography', 367, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hölzel,Norbert', 501, 'Institute for Landscape Ecology', 368, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hamer,Ute', 502, 'Institute for Landscape Ecology', 369, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Assistants study group Hölzel', 504, 'Institute for Landscape Ecology', 371, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Kleinebecker,Till', 503, 'Institute for Landscape Ecology', 370, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Lütke,Petra', 506, 'Faculty 14', 373, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Zens,Christiane', 508, 'Dean', 375, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Krull,Jutta', 509, 'Dean', 376, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Berger,Sina', 512, 'Institute for Landscape Ecology', 380, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Ho,Nguyen', 515, 'Institute for Landscape Ecology', 381, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meyer,Claudia', 518, 'Institute for Landscape Ecology', 382, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Klaus,Valentin', 522, 'Institute for Landscape Ecology', 386, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Gilhaus,Kristin', 521, 'Institute for Landscape Ecology', 385, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Weking,Sarah', 519, 'Institute for Landscape Ecology', 384, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Klemm,Otto', 535, 'Institute for Landscape Ecology', 387, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fartmann,Thomas', 537, 'Institute for Landscape Ecology', 389, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Löffler,Franz', 539, 'Institute for Landscape Ecology', 391, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Helbing,Felix', 539, 'Institute for Landscape Ecology', 390, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Stuhldreher,Gregor', 540, 'Institute for Landscape Ecology', 392, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Dieker,Petra', 540, 'Institute for Landscape Ecology', 393, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('El-Madany,Tarek', 542, 'Institute for Landscape Ecology', 394, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Tibebe,Degefie', 544, 'Institute for Landscape Ecology', 396, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Borchard,Fabian', 546, 'Institute for Landscape Ecology', 397, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Seminar 242', 242, 'Seminar room', 425, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 424, 'Institute for Landscape Ecology', 447, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Keplin,Beate', 2, 'Common section', 207, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Seuter,Matthias', 238, 'Institute for Geoinformatics', 508, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Böhmichen,Jeanine', 436, 'Institute for Landscape Ecology', 512, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Rupprecht,Denise', 521, 'Institute for Landscape Ecology', 516, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Li,Rui', 108, 'Institute for Geoinformatics', 235, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schwering,Angela', 106, 'Institute for Geoinformatics', 234, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hortig,Bianca', 105, 'Dean Chemistry', 233, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Humayun,Imaduddin', 104, 'Institute for Geoinformatics', 231, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Bartoschek,Thomas', 104, 'Institute for Geoinformatics', 232, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Mink,Ulrike', 103, 'Dean Chemistry', 230, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Rohtermundt,Christopher', 102, 'Institute for Geoinformatics', 229, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Runde,Marius Maria', 111, 'Institute for Geoinformatics', 239, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fuest,Stefan', 111, 'Institute for Geoinformatics', 238, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Chipofya,Malumbo', 109, 'Institute for Geoinformatics', 236, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Scholar,Erasmus', 248, 'Institute for Geoinformatics', 302, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schiestel,Nicholas', 245, 'Institute for Geoinformatics', 300, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schrüfer,Gabriele', 231, 'Institute for Didactics of Geography', 289, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Brinkert,Annika', 203, 'Institute for Landscape Ecology', 272, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 430, 'Institute for Landscape Ecology', 452, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 433, 'Institute for Landscape Ecology', 453, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 434, 'Institute for Landscape Ecology', 454, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 435, 'Institute for Landscape Ecology', 455, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Map Collection', 0.01, 'Library', 401, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('First aid room (Erste Hilfe)', 18, 'First aid room (Erste Hilfe)', 415, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Sulmann,Peter', 7, 'Electronic Factory', 213, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Broder,Tanja', 439, 'Institute for Landscape Ecology', 359, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('StudLab 130', 130, 'StudLab', 419, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Tappe,Melanie', 418, 'Institute for Landscape Ecology', 349, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fleischer,Elisa', 548, 'Institute for Landscape Ecology', 400, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Streitberger,Merle', 547, 'Institute for Landscape Ecology', 399, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Erasmus-Room', 211, 'Common section', 423, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room', 205, 'Chemistry and Pharmacy', 422, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('PC-Room', 201, 'Institute for Geoinformatics', 421, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room small 511', 511, 'Meeting', 460, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Seminar 513', 513, 'Seminar room', 461, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Münchberger,Wiebke', 512, 'Institute for Landscape Ecology', 378, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Teaching evaluation: Petra Lütke, Niklas Hardenacke', 507, 'Institute for Geography', 458, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Hardenacke,Niklas', 507, 'Institute for Geography', 459, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Library', 321, 'Library', 435, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Rock collection', 320, 'Fossil botany', 434, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Students', 319, 'Fossil botany', 433, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Fossil botany', 318, 'Fossil botany', 432, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Krajewski,Christian', 305, 'Institute for Geography', 311, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('SocioLab', 310, 'Institute for Geography', 431, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Staacke,Gerald', 313, 'Institute for Geography', 319, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Arndt,Witold', 448, 'Institute for Landscape Ecology', 365, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Secretary,Geographic commission', 406, 'Geographic commission', 341, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room large 455', 455, 'Meeting', 456, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 428, 'Institute for Landscape Ecology', 451, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room large 255', 255, 'Meeting', 428, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Meeting room large 147', 147, 'Meeting', 420, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Group room Library 0.18', 0.18, 'Library', 408, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Library hall 0.10', 0.10, 'Library', 202, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Ataei,Mehrnaz', 240, 'Institute for Geoinformatics', 509, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Bonaiuti,Simona', 439, 'Institute for Landscape Ecology', 513, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Schaller,Carsten', 544, 'Institute for Landscape Ecology', 517, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Konkol,Markus', 135, 'Institute for Geoinformatics', 505, 'p');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 534, 'Institute for Landscape Ecology', 470, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 533, 'Institute for Landscape Ecology', 469, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 532, 'Institute for Landscape Ecology', 468, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 528, 'Institute for Landscape Ecology', 467, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 527, 'Institute for Landscape Ecology', 466, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 526, 'Institute for Landscape Ecology', 465, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 525, 'Institute for Landscape Ecology', 464, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 524, 'Institute for Landscape Ecology', 463, 'r');
INSERT INTO "GEO1" ("Name", "Room", "Affiliation", "ID", "Type") VALUES ('Laboratory', 523, 'Institute for Landscape Ecology', 462, 'r');
